# Generated by Django 5.1 on 2024-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
