# Generated by Django 5.1 on 2024-08-24 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
