# Generated by Django 5.1 on 2024-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
